<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <EnableHarmony>true</EnableHarmony>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <BundleExtraAssemblies>ThirdParty</BundleExtraAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Pathoschild.Stardew.ModBuildConfig" Version="4.*" />
    <PackageReference Include="WebSocketSharp-netstandard" Version="1.0.1" />
  </ItemGroup>

  <ItemGroup>
    <None Update="data\knowledge\wiki\**\*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
